POST http://localhost:3001/api/procedure
Content-Type: application/json

{
    "surname": "Иванова1",
    "name": "Марина1",
    "birthday": "01-01-1990",
    "city": "Москва",
    "dept_name": "Разработка",
    "comp_name": "Газпром"
}
